# title: "Waqar Hassan"
# description: "Data Scientist | Machine Learning Researcher"
# baseurl: ""
# url: "https://yourusername.github.io"
# theme: minimal-mistakes-jekyll

# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-seo-tag

# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: single

title: "Waqar Hassan's Portfolio"
description: "Data Scientist | Machine Learning Researcher"
baseurl: ""
# url: "https://waqarhassan.github.io"  # Replace with your GitHub username
url: "https://waqar351.github.io/whassan.github.io"

theme: "minimal-mistakes-jekyll"  # If you are using the Minimal Mistakes theme

# Social Links
social_links:
  - icon: "github"
    url: "https://github.com/<waqar351>"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/<your-linkedin-profile>"
  - icon: "twitter"
    url: "https://twitter.com/<your-twitter-profile>"

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"

