title: "Waqar Hassan"
description: "Data Scientist | Machine Learning Researcher"
baseurl: ""
url: "https://yourusername.github.io"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
